// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvkcUbOD1uIvR1ZM6gX_G12GFauwsZaZM',
    appId: '1:251093116694:web:562b743df08774d6d31237',
    messagingSenderId: '251093116694',
    projectId: 'demoocrazure',
    authDomain: 'demoocrazure.firebaseapp.com',
    storageBucket: 'demoocrazure.appspot.com',
    measurementId: 'G-0QSQ43H3Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEt9zhfr3gr4GX4GWDhFRaYAJvVEY9vAw',
    appId: '1:251093116694:android:10113879d86387f2d31237',
    messagingSenderId: '251093116694',
    projectId: 'demoocrazure',
    storageBucket: 'demoocrazure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwhMSb3vvlp7RIv8hsne1cJiAWJ9NplYk',
    appId: '1:251093116694:ios:87f71e828fa51439d31237',
    messagingSenderId: '251093116694',
    projectId: 'demoocrazure',
    storageBucket: 'demoocrazure.appspot.com',
    iosBundleId: 'com.example.demoocrcamera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwhMSb3vvlp7RIv8hsne1cJiAWJ9NplYk',
    appId: '1:251093116694:ios:0f6feee5c90ad6c7d31237',
    messagingSenderId: '251093116694',
    projectId: 'demoocrazure',
    storageBucket: 'demoocrazure.appspot.com',
    iosBundleId: 'com.example.demoocrcamera.RunnerTests',
  );
}
